---
title: "Alaska's National Parks"
output: html_document
---

Goal: Visits to Alaska's National Parks by year in an interesting projection.

```{r lib}

library(tidyverse)
library(sf)
library(rnaturalearth)
library(viridis)
library(gganimate)

```

```{r dat}

# https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-09-17
dat = read_csv("par.csv") %>% 
  filter(state == "AK",
         year != "Total") %>% 
  dplyr::select(year,  
         parkname, 
         visitors) %>% 
  mutate(year = as.numeric(year))

# https://catalog.data.gov/dataset/national-parks
nps = 
  st_read("nps/nps_boundary.shp") %>% 
  filter(STATE == "AK") %>% 
  dplyr::select(PARKNAME) %>% 
  mutate(parkname = as.character(PARKNAME)) %>% 
  select(-PARKNAME)

# smoosh
jat = dat %>% 
  full_join(nps, by = "parkname") %>% 
  st_sf()

crs = "+init=epsg:3338"

pat = jat %>% 
  filter(year > 1954) %>% 
  st_transform(crs = crs)

# naturalearth
ak = 
  ne_download(scale = 10, 
              type = "admin_1_states_provinces",
              returnclass = "sf") %>% 
  filter(name == "Alaska") %>% 
  select(name, admin) %>% 
  st_transform(crs = crs)

```

```{r vis}

vis = 
  ggplot() +
  geom_sf(data = ak,
          fill = "grey75",
          color = NA) +
  geom_sf(data = pat,
          aes(fill = log(visitors)),
          color = NA) +
  scale_fill_viridis_c(option = "A") +
  labs(title = 'Visitors to Alaskan National Parks in {current_frame} (Natural Log)') +
  guides(fill = guide_colorbar(barwidth = 30,
                               barheight = 1,
                               ticks = FALSE)) +
  theme_void() +
  theme(legend.position = "bottom",
        legend.title=element_blank()) +
  transition_manual(frames = year) +
  enter_fade() +
  exit_fade()

anim_save("par_vis.gif", 
          animate(vis,
                  fps = 30,
                  duration = 30,
                  width = 1200,
                  height = 800))

```



