---
title: "Transistor Tuesday"
output: html_document
---

Goal: Text.


Packages
```{r pac}

library(tidyverse)
library(broom)
library(viridis)
library(gridExtra)
library(ggridges)

```

Data and Wrangling
```{r set}

cpu = read_csv("cpu.csv")

gpu = read_csv("gpu.csv") %>% 
  select(-manufacturer_s, 
         -ref) %>% 
  rename(designer = designer_s) # Suppose designer and manufacturer are the same for our purposes.

ram = read_csv("ram.csv") %>% 
  select(-capacity_bits,
         -bit_units,
         -ram_type, 
         -ref) %>% 
  rename(processor = chip_name,
         designer = manufacturer_s) # Suppose designer and manufacturer are the same for our purposes.

dat = bind_rows(list(CPU = cpu, 
                     GPU = gpu, 
                     RAM = ram), 
                .id = "Component")

```

Analysis
```{r}

y0 = min(na.omit(dat$date_of_introduction)) # Get base year.

dat = dat %>% 
  mutate(y = date_of_introduction - y0, # Adjust years to run from 0.
         logt = log(transistor_count)) # Add log of transistor column for a quick join.

mod = lm(log(transistor_count) ~ y, # Run model for linear fit.
         dat)

dat = dat %>% 
  left_join(augment(mod),
            by = c("y", 
                   "logt" = "log.transistor_count.")) %>% 
  select(-.rownames, 
         -.hat, 
         -.sigma, 
         -.cooksd)
  
```

Visualization
```{r vis}

# Set palettes from viridis for manual use.
pal_col = inferno(3, 
                  begin = 0.40, 
                  end = 0.80)

pal_fil = inferno(3, 
                  begin = 0.40, 
                  end = 0.80,
                  alpha = 0.75)

# Raw
raw = 
  ggplot(data = dat) +
  geom_jitter(aes(x = date_of_introduction,
                  y = log(transistor_count),
                  color = Component,
                  fill = Component),
             shape = 21) +
  geom_rug(aes(x = date_of_introduction,
               y = log(transistor_count),
               color = Component),
           position = "jitter") +
  scale_color_manual(values = pal_col) +
  scale_fill_manual(values = pal_fil) +
  labs(x = "",
       y = "Transistors (Log Scale)",
       title = "A (Raw Data)") +
  scale_x_continuous(breaks = c(1960, 1975, 1990, 2005, 2020),
                     limits = c(1960, 2020)) +
  theme_classic() +
  theme(legend.position = "none")

# Model, Standard Errors.
ste = 
  ggplot(data = dat) +
  geom_ribbon(aes(x = date_of_introduction,
                  ymin = .fitted - .se.fit,
                  ymax = .fitted + .se.fit),
              color = "grey75",
              fill = "grey50") +
  geom_line(aes(x = date_of_introduction,
                y = .fitted)) +
  geom_point(aes(x = date_of_introduction,
                 y = log(transistor_count),
                 color = Component,
                 fill = Component),
             shape = 16,
             alpha = 0.50) +
  geom_rug(aes(x = date_of_introduction,
               y = log(transistor_count),
               color = Component),
           position = "jitter") +
  scale_color_manual(values = pal_col) +
  scale_fill_manual(values = pal_fil) +
  scale_x_continuous(breaks = c(1960, 1975, 1990, 2005, 2020),
                     limits = c(1960, 2020)) +
  labs(x = "", 
       y = "",
       title = "B (Linear Fit)") +
  theme_classic() +
  theme(legend.position = "none")

# Model, Residuals.
res = 
  ggplot(data = dat) + 
  geom_segment(aes(x = date_of_introduction,
                   xend = date_of_introduction,
                   y = log(transistor_count),
                   yend = .fitted),
               color = "grey10") +
  geom_point(aes(x = date_of_introduction,
                 y = log(transistor_count),
                 color = Component,
                 fill = Component),
             shape = 16) +
  geom_point(aes(x = date_of_introduction,
                 y = .fitted),
             color = "grey10") +
  geom_rug(aes(x = date_of_introduction,
               y = log(transistor_count),
               color = Component),
           position = "jitter") +
  scale_color_manual(values = pal_col) +
  scale_fill_manual(values = pal_fil) +
  scale_x_continuous(breaks = c(1960, 1975, 1990, 2005, 2020),
                     limits = c(1960, 2020)) +
  labs(x = "", 
       y = "",
       title = "C (Residuals)") +
  theme_classic()

# Leftover: clean up breaks, legends, letters, call-outs
  
vis_reg = arrangeGrob(raw, 
                      ste, 
                      res, 
                      nrow = 1)

ggsave("vis_reg.png", 
       vis_reg, 
       dpi = 300,
       width = 9.5,
       height = 4.5)

# Ridges!
#  Filter out products outside the 0.75 from more prolific designers.
dat_des = dat %>% 
  add_count(designer) %>% 
  top_frac(0.75, n)

#  Plot densities of products over residuals for the more prolific designers.
rid_des = 
  ggplot(data = dat_des) +
  geom_density_ridges(aes(x = .resid,
                          y = designer,
                          fill = designer),
                      color = "black",
                      alpha = 0.75,
                      stat = "binline") +
  scale_fill_viridis_d(option = "B") +
  scale_x_continuous(breaks = c(-6, -3, 0, 3, 6)) +
  labs(x = "",
       y = "",
       title = "D (Designers)") +
  theme_classic() +
  theme(legend.position = "none")

#  Plot densities of products over residuals by component.
rid_com =
  ggplot(data = dat) +
  geom_density_ridges(aes(x = .resid,
                          y = Component,
                          fill = Component),
                      color = "black",
                      alpha = 0.75,
                      stat = "binline") +
  scale_fill_manual(values = pal_col) +
  scale_x_continuous(breaks = c(-6, -3, 0, 3, 6)) +
  labs(x = "Residuals",
       y = "",
       title = "E (Components)") +
  theme_classic() +
  theme(legend.position = "none")

#  Plot densities of products over residuals by decade.
dat_dec = dat %>% 
  mutate(dec = as.factor(ceiling((y + 1) / 10))) %>% 
  drop_na(dec)

pal_col_six = inferno(6, 
                      begin = 0.40, 
                      end = 0.80)

rid_dec = 
  ggplot(data = dat_dec) +
  geom_density_ridges(aes(x = .resid,
                          y = dec,
                          fill = dec),
                      color = "black",
                      alpha = 0.75,
                      stat = "binline") +
  scale_fill_manual(values = pal_col_six) +
  scale_x_continuous(breaks = c(-6, -3, 0, 3, 6)) +
  labs(x = "",
       y = "",
       title = "F (Decades)") +
  theme_classic() +
  theme(legend.position = "none")

#  Leftover: labels, legend order, call-outs

vis_res = arrangeGrob(rid_des, 
                      rid_com, 
                      rid_dec, 
                      nrow = 1) 

ggsave("vis_res.png", 
       vis_res, 
       dpi = 300,
       width = 9.5,
       height = 4.5)

```

