---
title: "Nuclear Tuesday"
output: html_document
---

Goal: Text.


Packages
```{r pac}

library(readr)
library(dplyr)
library(magrittr)
library(sp)
library(sf)
library(rnaturalearth)
library(ggplot2)
library(gganimate)
library(gifski)
library(png)
library(transformr)

```

Data and Wrangling
```{r set}

# Define Coordinate Reference System.
crs = "+proj=robin" #4326

# Download Tidy Tuesday data.
#dat = read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-20/nuclear_explosions.csv")
# Save Tidy Tuesday data.
#write_csv(dat, "nuc.csv")
# Read and transform Tidy Tuesday data.
data = 
  read_csv("nuc.csv") %>% 
  select(longitude,
         latitude, 
         year, 
         id_no,
         yield_upper) %>% 
  na.omit() %>% 
  st_as_sf(coords = c("longitude", "latitude"), 
           crs = "+proj=longlat") %>% 
  st_transform(crs)

# Download and transform Natural Earth data.
land = 
  ne_download(scale = 50, 
              type = "land", 
              category = "physical", 
              returnclass = "sf") %>% 
  st_transform(crs)

ocean = 
  ne_download(scale = 50, 
              type = "ocean", 
              category = "physical", 
              returnclass = "sf") %>% 
  st_transform(crs)

lakes = 
  ne_download(scale = 50, 
              type = "lakes", 
              category = "physical", 
              returnclass = "sf") %>% 
  st_transform(crs)

```

Visualization
```{r vis}

# Map layer
# Nuclear layer
# Edges
# Animation

map = 
ggplot() + 
  geom_sf(data = ocean,
          fill = "slategray1",
          color = NA) +
    geom_sf(data = land,
            fill = "slategray",
            color = NA) +
    geom_sf(data = lakes,
            fill = "slategray1",
            color = NA) +
  geom_sf(data = data, 
          aes(size = yield_upper),
          color = "firebrick4",
          shape = 10) +
  geom_rug(data = data,
           aes()) +
  scale_color_distiller(palette = "Reds") +
  #labs(caption = "Here's your caption.", title = "Here's your title.") +
  theme_classic()

ani = map +
  transition_states(year)#,
                    transition_length = 2,
                    state_length = 1)

```

